CREATE TABLE REPORT_RUN_SNAPSHOTS (
    RUN_ID VARCHAR2(36 CHAR) NOT NULL,
    SCHEMA_JSON CLOB NOT NULL,
    SCHEMA_HASH CHAR(64 CHAR) NOT NULL,
    ROW_COUNT NUMBER(19, 0) DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(16 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REPORT_RUN_SNAPSHOTS PRIMARY KEY (RUN_ID),
    CONSTRAINT CK_REPORT_RUN_SNAPSHOTS_STATUS CHECK (STATUS IN ('WRITING', 'READY'))
);

CREATE TABLE REPORT_RUN_SNAPSHOT_ROWS (
    RUN_ID VARCHAR2(36 CHAR) NOT NULL,
    ROW_NO NUMBER(19, 0) NOT NULL,
    VALUES_JSON CLOB NOT NULL,
    CONSTRAINT PK_REPORT_RUN_SNAPSHOT_ROWS PRIMARY KEY (RUN_ID, ROW_NO),
    CONSTRAINT FK_REPORT_RUN_SNAPSHOT_ROWS_RUN FOREIGN KEY (RUN_ID)
        REFERENCES REPORT_RUN_SNAPSHOTS (RUN_ID) ON DELETE CASCADE
);
