export const weatherChartPalette = {
  precipitation: 'var(--color-chart-precipitation)',
  precipitationAverage: 'var(--color-chart-emerald)',
  precipitationLight: 'var(--color-chart-green)',
  precipitationDark: 'var(--color-chart-forest)',
  temperature: 'var(--color-chart-amber)',
  apparentTemperature: 'var(--color-chart-red)',
  probability: 'var(--color-chart-blue)',
  probabilityDark: 'var(--color-chart-violet)',
  humidity: 'var(--color-chart-teal)',
  humidityDark: 'var(--color-chart-navy)',
  wind: 'var(--color-chart-slate)',
  windDark: 'var(--color-chart-slate-dark)',
  windDeep: 'var(--color-chart-charcoal)',
  life: [
    'var(--color-chart-amber)',
    'var(--color-chart-emerald)',
    'var(--color-chart-blue)',
    'var(--color-chart-red)',
    'var(--color-chart-violet)',
    'var(--color-chart-teal)',
    'var(--color-chart-slate)',
    'var(--color-chart-rust)',
    'var(--color-chart-rose)',
    'var(--color-chart-olive)',
    'var(--color-chart-indigo)',
    'var(--color-chart-brown)',
  ],
} as const
